excluded:
  - Pods
  
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

file_header:
  required_pattern: |
                    \/\/  TDD sample app MarvelBrowser-Swift by Jon Reid, https:\/\/qualitycoding\.org\/
                    \/\/  Copyright 2017 Jonathan M\. Reid\. See LICENSE\.txt

trailing_comma:
  mandatory_comma: true

trailing_whitespace:
  ignores_empty_lines: true
